name: Docker CI build docker images and push

on:
  push:
    branches: [dev, main]
    paths:
      - 'frontend/**'
      - 'backend1/**' 
      - 'backend2/**'
      - '.github/workflows/**'
  pull_request:
    branches: [dev, main]
    types: [opened, synchronize, reopened]
    paths:
      - 'frontend/**'
      - 'backend1/**'
      - 'backend2/**'
      - '.github/workflows/**'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend1/**'
              - 'backend2/**'


  build-frontend:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || needs.changes.outputs.frontend == 'true')  # if this condition is true, run this job otherwise skip it
    needs: changes
    runs-on: v1  # frontend runner
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    outputs:
      new_version: ${{ steps.get-version.outputs.new_version }}

    steps:
      - uses: actions/checkout@v4

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_UNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Get version
        id: get-version
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            git fetch --tags
            latest_version=$(git tag --sort=-version:refname | head -n 1)
            
            if [ -z "$latest_version" ]; then
              echo "Using default version 1.0.0 because no tags were found"
              new_version="1.0.0"
            else
              commits=$(git log ${latest_version}..HEAD --oneline)
              
              if echo "$commits" | grep -q -E "(BREAKING CHANGE|!:|feat!:|fix!:)"; then
                new_version=$(semver bump major "$latest_version")
              elif echo "$commits" | grep -q -E "^[a-f0-9]+ feat:"; then
                new_version=$(semver bump minor "$latest_version")
              else
                new_version=$(semver bump patch "$latest_version")
              fi
            fi
            
            if git ls-remote --tags origin | grep -q "refs/tags/$new_version"; then
              echo "Tag $new_version already exists. Skipping tagging."
            else
              echo "Creating new tag: $new_version"
              git tag "$new_version"
              git push origin "$new_version"
            fi
            
          else
            new_version="${{ github.ref_name }}-${{ github.sha }}"
          fi
          
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          echo "Using version: $new_version"
        
      - name: Cache Frontend Build
        id: cache-frontend-build
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-dep-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-frontend-dep

      - name: Build Frontend App
        env:
          VITE_APP_VERSION: ${{ steps.get-version.outputs.new_version }}
          VITE_CLERK_PUBLISHABLE_KEY: ${{ vars.VITE_CLERK_PUBLISHABLE_KEY }}
          VITE_URL_ADDR: ${{ vars.VITE_URL_ADDR }}
          VITE_BASE_PATH: /blog-app-fellowship/
        run: |
          yarn --cwd frontend install --network-timeout 600000
          yarn add @types/node
          yarn --cwd frontend build 

      - name: Upload Frontend Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-${{ steps.get-version.outputs.new_version }}
          path: frontend/dist/


      - name: Build and Push Frontend
        # if: steps.cache-frontend-build.outputs.cache-hit != 'true'
        run: |
          docker build \
            --build-arg VITE_CLERK_PUBLISHABLE_KEY=${{ vars.VITE_CLERK_PUBLISHABLE_KEY }} \
            --build-arg VITE_URL_ADDR=${{ vars.VITE_URL_ADDR }} \
            -f ./frontend/frontend.Dockerfile \
            -t safalkarki/frontend:${{ steps.get-version.outputs.new_version }} ./frontend

          docker push safalkarki/frontend:${{ steps.get-version.outputs.new_version }}

      - name: Export Frontend Docker Image
        run: |
          mkdir -p docker-exports
          docker save safalkarki/frontend:${{ steps.get-version.outputs.new_version }} -o docker-exports/frontend-${{ steps.get-version.outputs.new_version }}.tar
      
      - name: Copy Docker image export to frontend dist folder
        run: |
          mkdir -p frontend/dist/docker-images
          cp docker-exports/frontend-${{ steps.get-version.outputs.new_version }}.tar frontend/dist/docker-images/

          
      - name: Upload Frontend Docker Image Export
        uses: actions/upload-artifact@v4
        with:
          name: frontend-docker-image-${{ steps.get-version.outputs.new_version }}
          path: docker-exports/frontend-${{ steps.get-version.outputs.new_version }}.tar

  build-backends:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || needs.changes.outputs.backend == 'true')
    needs: changes
    runs-on: v2   # backend runner
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    outputs:
      new_version: ${{ steps.get-version.outputs.new_version }}

    steps:
      - uses: actions/checkout@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_UNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Get version
        id: get-version
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            git fetch --tags
            latest_version=$(git tag --sort=-version:refname | head -n 1)
            
            if [ -z "$latest_version" ]; then
              echo "Using default version 1.0.0 because no tags were found"
              new_version="1.0.0"
            else
              commits=$(git log ${latest_version}..HEAD --oneline)
              
              if echo "$commits" | grep -q -E "(BREAKING CHANGE|!:|feat!:|fix!:)"; then
                new_version=$(semver bump major "$latest_version")
              elif echo "$commits" | grep -q -E "^[a-f0-9]+ feat:"; then
                new_version=$(semver bump minor "$latest_version")
              else
                new_version=$(semver bump patch "$latest_version")
              fi
            fi
            
            if git ls-remote --tags origin | grep -q "refs/tags/$new_version"; then
              echo "Tag $new_version already exists. Skipping tagging."
            else
              echo "Creating new tag: $new_version"
              git tag "$new_version"
              git push origin "$new_version"
            fi
            
          else
            new_version="${{ github.ref_name }}-${{ github.sha }}"
          fi
          
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          echo "Using version: $new_version"
      
      - name: Cache Backend Build
        id: cache-backend-build
        uses: actions/cache@v4
        with: 
          path: |
            backend1/node_modules
            backend2/node_modules
          key: ${{ runner.os }}-backend-dep-${{ hashFiles('backend1/yarn.lock', 'backend2/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-backend-dep

      - name: Build Backend App
        run: |
          yarn --cwd backend1 install --network-timeout 600000
          yarn --cwd backend1 build
          yarn --cwd backend2 install --network-timeout 600000
          yarn --cwd backend2 build

      - name: Upload Backend Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build-${{ steps.get-version.outputs.new_version }}
          path: |
            backend1/dist/
            backend2/dist/

      - name: Build and Push Backend1
        # if: steps.cache-backend-build.outputs.cache-hit != 'true'
        run: |
          docker build -f ./backend1/backend1.Dockerfile -t safalkarki/backend1:${{ steps.get-version.outputs.new_version }} ./backend1
          docker push safalkarki/backend1:${{ steps.get-version.outputs.new_version }}

      - name: Build and Push Backend2
        run: |
          docker build -f ./backend2/backend2.Dockerfile -t safalkarki/backend2:${{ steps.get-version.outputs.new_version }} ./backend2
          docker push safalkarki/backend2:${{ steps.get-version.outputs.new_version }}

      - name: Export Backend Docker Images
        run: |
          mkdir -p docker-exports
          docker save safalkarki/backend1:${{ steps.get-version.outputs.new_version }} -o docker-exports/backend1-${{ steps.get-version.outputs.new_version }}.tar
          docker save safalkarki/backend2:${{ steps.get-version.outputs.new_version }} -o docker-exports/backend2-${{ steps.get-version.outputs.new_version }}.tar

      - name: Copy Backend Docker image export to frontend dist folder
        run: |
          mkdir -p frontend/dist/docker-images
          cp docker-exports/backend1-${{ steps.get-version.outputs.new_version }}.tar frontend/dist/docker-images/
          cp docker-exports/backend2-${{ steps.get-version.outputs.new_version }}.tar frontend/dist/docker-images/

      - name: Upload Backend Docker Image Exports
        uses: actions/upload-artifact@v4
        with:
          name: backend-docker-images-${{ steps.get-version.outputs.new_version }}
          path: docker-exports/

  pr-checks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Conventional Commit Check
        uses: wagoid/commitlint-github-action@v5

      - name: Check for sensitive data in env files
        run: |
          echo "Checking for exposed secrets in .env files..."
          if grep -r "sk_test_\|pk_test_\|sk_live_\|pk_live_" --include="*.env" . 2>/dev/null | grep -v "placeholder\|example\|your_key_here"; then
            echo "Found potential exposed secrets in .env files"
            exit 1
          else
            echo "No exposed secrets found"
          fi

      - name: Dockerfile existence check
        run: |
          echo "Checking if required Dockerfiles exist..."
          missing_files=0
          
          if [[ ! -f "./frontend/frontend.Dockerfile" ]]; then
            echo "frontend/frontend.Dockerfile not found"
            missing_files=1
          fi
          
          if [[ ! -f "./backend1/backend1.Dockerfile" ]]; then
            echo "backend1/backend1.Dockerfile not found"
            missing_files=1
          fi
          
          if [[ ! -f "./backend2/backend2.Dockerfile" ]]; then
            echo "backend2/backend2.Dockerfile not found"
            missing_files=1
          fi
          
          if [ $missing_files -eq 1 ]; then
            exit 1
          fi
          
          echo "All required Dockerfiles found"

  deploy:
    needs: [build-frontend, build-backends]
    if: github.ref_name == 'dev' || github.ref_name == 'main'
    runs-on: v1
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop $(docker container ps -q)
            docker container prune -f

            echo "Starting postgres.."
            
            docker rm -f postgres >/dev/null 2>&1 || true
            docker network inspect my-backend-network >/dev/null 2>&1 || docker network create my-backend-network

            docker run -d --rm --init \
            --name postgres \
            --network my-backend-network \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            -v pgdata:/var/lib/postgresql/data \
            -p 5432:5432 \
            postgres:latest

            echo "Deploying to server..."

            docker stop frontend backend1 backend2 2>/dev/null || true
            docker rm frontend backend1 backend2 2>/dev/null || true

            echo "Frontend version: ${{ needs.build-frontend.outputs.new_version }}"
            echo "Backend1 version: ${{ needs.build-backends.outputs.new_version }}"
            echo "Backend2 version: ${{ needs.build-backends.outputs.new_version }}"

            docker pull safalkarki/frontend:${{ needs.build-frontend.outputs.new_version }}
            docker pull safalkarki/backend1:${{ needs.build-backends.outputs.new_version }}
            docker pull safalkarki/backend2:${{ needs.build-backends.outputs.new_version }}

            docker run -d --name frontend -p 80:80 safalkarki/frontend:${{ needs.build-frontend.outputs.new_version }}
            docker run -d --name backend1 -p 3000:3000 \
            --network my-backend-network \
            -e PORT=${{ vars.BACKEND1_PORT }} \
            -e DB_PORT=${{ vars.DB_PORT }} \
            -e DB_HOST=${{ vars.DB_HOST }} \
            -e DB_USER=${{ secrets.BACKEND1_DB_USER }} \
            -e DB_PASSWORD=${{ secrets.BACKEND1_DB_PASSWORD }} \
            -e DB_NAME=${{ vars.DB_NAME }} \
            -e DB_CLIENT=${{ vars.DB_CLIENT }} \
            -e NODE_ENV=${{ vars.NODE_ENV }} \
            -e CLERK_PUBLISHABLE_KEY=${{ secrets.BACKEND1_CLERK_PUBLISHABLE_KEY }} \
            -e CLERK_SECRET_KEY=${{ secrets.BACKEND1_CLERK_SECRET_KEY }} \
            safalkarki/backend1:${{ needs.build-backends.outputs.new_version }} 


            docker run -d --name backend2 -p 3001:3001 \
            --network my-backend-network \
            -e PORT=${{ vars.BACKEND2_PORT }} \
            -e DB_PORT=${{ vars.DB_PORT }} \
            -e DB_HOST=${{ vars.DB_HOST }} \
            -e DB_USER=${{ secrets.BACKEND2_DB_USER }} \
            -e DB_PASSWORD=${{ secrets.BACKEND2_DB_PASSWORD }} \
            -e DB_NAME=${{ vars.DB_NAME }} \
            -e DB_CLIENT=${{ vars.DB_CLIENT }} \
            -e NODE_ENV=${{ vars.NODE_ENV }} \
            -e CLERK_PUBLISHABLE_KEY=${{ secrets.BACKEND2_CLERK_PUBLISHABLE_KEY }} \
            -e CLERK_SECRET_KEY=${{ secrets.BACKEND2_CLERK_SECRET_KEY }} \
            safalkarki/backend2:${{ needs.build-backends.outputs.new_version }}

            echo "Deployment completed successfully"

  create-release:
      needs: [build-frontend, build-backends]
      if: github.ref_name == 'main'
      runs-on: ubuntu-latest
      steps:
        - name: Download frontend artifact
          uses: actions/download-artifact@v4
          with:
            name: frontend-docker-image-${{ needs.build-frontend.outputs.new_version }}
            path: docker-artifacts/frontend

        - name: Download backend artifacts
          uses: actions/download-artifact@v4
          with:
            name: backend-docker-images-${{ needs.build-backends.outputs.new_version }}
            path: docker-artifacts/backend

        - name: Create GitHub Release
          uses: softprops/action-gh-release@v1
          with:
            tag_name: ${{ needs.build-frontend.outputs.new_version }}
            name: Release ${{ needs.build-frontend.outputs.new_version }}
            draft: false
            prerelease: false
            files: |
              docker-artifacts/frontend/*.tar
              docker-artifacts/backend/*.tar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-frontend-pages:
    if: github.ref_name == 'main'
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build-${{ needs.build-frontend.outputs.new_version }}
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist

  trivy-scan:
    if: github.ref_name == 'main'
    needs: [build-frontend, build-backends]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Trivy HTML template
        run: |
          mkdir -p contrib
          wget -O contrib/html.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl

      - name: Run Trivy vulnerability scanner on Frontend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'safalkarki/frontend:${{ needs.build-frontend.outputs.new_version }}'
          format: 'template'
          template: '@contrib/html.tpl'
          output: 'frontend-scan.html'

      - name: Run Trivy vulnerability scanner on Backend1 image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'safalkarki/backend1:${{ needs.build-backends.outputs.new_version }}'
          format: 'template'
          template: '@contrib/html.tpl'
          output: 'backend1-scan.html'

      - name: Run Trivy vulnerability scanner on Backend2 image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'safalkarki/backend2:${{ needs.build-backends.outputs.new_version }}'
          format: 'template'
          template: '@contrib/html.tpl'
          output: 'backend2-scan.html'

      - name: Move scan reports to directory
        run: |
          mkdir -p scan-reports
          mv frontend-scan.html scan-reports/
          mv backend1-scan.html scan-reports/
          mv backend2-scan.html scan-reports/

      - name: Upload scan reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-reports-${{ needs.build-frontend.outputs.new_version }}
          path: scan-reports/

  semgrep-scan:
    needs: [build-frontend, build-backends]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep scan
        run: |
          python -m pip install semgrep
          semgrep scan --text --text-output=semgrep.txt

      - name: Move to directory
        run: |
            mkdir -p scan-reports
            mv semgrep.txt scan-reports/

      - name: Upload Semgrep scan results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-scan-results-${{ needs.build-frontend.outputs.new_version }}
          path: scan-reports/



  deploy-scan-reports:
    if: github.ref_name == 'main'
    needs: [build-frontend, trivy-scan]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download scan reports
        uses: actions/download-artifact@v4
        with:
          name: security-scan-reports-${{ needs.build-frontend.outputs.new_version }}
          path: scan-reports

      - name: Deploy scan reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: scan-reports
          destination_dir: scan
          keep_files: true  